[game]
round_end_pacifist = true
hostname = ":rocket: Lost Paradise - 3.0 :penguin: [18+][TTS]"
desc = "- Мы проект со средним требованием к отыгрышу с разрешенным ЕРП. \n- Наша цель это создание приятного времяпрепровождения для всех игроков не зависимо от их предпочитаемого геймлпея \n- Присоединяйтесь в наше Дискорд сообщество"
lobbyduration = 240
secret_weight_prototype = "SecretLP"
#map_pool = ""
soft_max_players = 111

[infolinks]
discord = "https://wiki.lost-paradise.space/discord"
github = "https://github.com/Lost-Paradise-Project/Main-Station"
wiki = "http://wiki.lost-paradise.space/"
website = "https://boosty.to/lost-paradise"

[game.panic_bunker]
enabled = true
show_reason = true
min_account_age = 10
min_overall_minutes = 0
enable_without_admins = true
disable_with_admins = true

[server]
rules_file = "LPPRuleset"

[hub]
tags = "lang:ru,region:eu_e,rp:med,18+"

[shuttle]
shipyard = false
auto_call_time = 90
# arrivals_map = "/Maps/_LP/Misc/paradise_terminal.yml"

[viewport]
maximum_width = 26

[netres]
store_deletion_days = 7
limit = 25.0

[admin]
admins_count_in_playercount = true
see_own_notes = true
discord_reply_prefix = "(ДС) "
bwoink_use_admin_ooc_color = true

[ahelp]
rate_limit_count = 2
rate_limit_period = 10

[supermatter]
rads_base = 1

[votekick]
enabled = false

[vote]
enabled = true
same_type_timeout = 300.0
timerrestart = 30
map_enabled = true
preset_enabled = true
restart_enabled = true

[build]
fork_id = "LPP"

[rules]
time = 180.0

#[announcer]
#list = ""

[discord]
rich_main_icon_id = "https://iili.io/f85IYyQ.png"

[interaction]
rate_limit_announce_admins_delay = -1

[jetpack]
enable_in_no_gravity = true

[glimmer]
enabled = false
